apiVersion: v1
kind: ConfigMap
metadata:
  name: weekly-report-config
  namespace: default
data:
  db-secret-name: "one-rds-credentials"
  app-config-secret-name: "weekly-report/app-config"
  aws-region: "ap-northeast-2"
  ses-sender-email: "noreply@aws11.shop"
  api-base-url: "https://api.aws11.shop"
