apiVersion: v1
kind: Service
metadata:
  name: weekly-report-service
  namespace: default
  labels:
    app: weekly-report
spec:
  type: ClusterIP
  selector:
    app: weekly-report
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
